### ISSUE TITLE
Chipped Incompatibility

### ISSUE THREAD

**Issue by jaeggr** [TagnumElite/ProjectE-Integration#114]
### Prerequisites

- [X] I am running the latest version (7.1.0)
- [X] I have made sure there is no duplicate issue

### Details

- MC Version: 1.20.1
- Mod Version: 7.1.0

## Description

The latest Chipped mod versions (newer than 3.0.1) cause the EMC engine to crash, and all EMC values are lost, including the base ProjectE items.

### To Reproduce
1. Install Chipped version newer than 3.0.1
2. Install ProjectE and ProjectE-Integration
3. Game will load, but all EMC values are gone.

## Logs

<details>
  <summary>Log</summary>

```
[10Feb2024 17:02:21.451] [main/ERROR] [moze_intel.projecte.PECore/]: Error calculating EMC values
java.lang.NoSuchFieldError: TINKERING_TABLE_TYPE
	at com.tagnumelite.projecteintegration.addons.ChippedAddon$ChippedMechanistWorkbenchMapper.canHandle(ChippedAddon.java:155) ~[ProjectE%20Integration-1.20.1-7.1.0.jar%23582!/:7.1.0]
	at moze_intel.projecte.emc.mappers.recipe.CraftingMapper.addMappings(CraftingMapper.java:65) ~[ProjectE-1.20.1-PE1.0.1.jar%23583!/:1.0.1]
	at moze_intel.projecte.emc.EMCMappingHandler.map(EMCMappingHandler.java:118) ~[ProjectE-1.20.1-PE1.0.1.jar%23583!/:1.0.1]
	at moze_intel.projecte.PECore.tagsUpdated(PECore.java:337) ~[ProjectE-1.20.1-PE1.0.1.jar%23583!/:1.0.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraft.server.ReloadableServerResources.m_206868_(ReloadableServerResources.java:90) ~[server-1.20.1-20230612.114412-srg.jar%23681!/:?]
	at net.minecraft.server.WorldLoader.m_244809_(WorldLoader.java:44) ~[server-1.20.1-20230612.114412-srg.jar%23681!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.Util.m_214652_(Util.java:783) ~[server-1.20.1-20230612.114412-srg.jar%23681!/:?]
	at net.minecraft.Util.m_214679_(Util.java:772) ~[server-1.20.1-20230612.114412-srg.jar%23681!/:?]
	at net.minecraft.server.Main.main(Main.java:166) ~[server-1.20.1-20230612.114412-srg.jar%23681!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.19.jar%2369!/:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.19.jar%2369!/:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.19.jar%2369!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```

</details>

**Comment by TagnumElite** [comment]
Should be fixed in `v7.1.1`
