### ISSUE TITLE
PneumaticCraft Integration Disables EMC

### ISSUE THREAD

**Issue by rallias** [TagnumElite/ProjectE-Integration#49]
### Prerequisites

- [x] I am running the latest version
- [x] I have made sure there is no duplicate issue

### Details

- MC Version: 1.8.2
- Mod Version: 5.0.0

## Description

EMC is broke, following in latest.log:

[00:19:25] [Render thread/ERROR]: Error calculating EMC values
java.lang.NoSuchFieldError: heatFrameCooling
        at com.tagnumelite.projecteintegration.addons.PneumaticCraftAddon$PCRHeatFrameCoolingMapper.canHandle(PneumaticCraftAddon.java:195) ~[projecte-integrati
on-1.18.2-5.0.0.jar%23295!/:5.0.0]
        at moze_intel.projecte.emc.mappers.recipe.CraftingMapper.addMappings(CraftingMapper.java:61) ~[ProjectE-1.18.2-PE1.0.1.jar%23294!/:1.0.1]
        at moze_intel.projecte.emc.EMCMappingHandler.map(EMCMappingHandler.java:116) ~[ProjectE-1.18.2-PE1.0.1.jar%23294!/:1.0.1]
        at moze_intel.projecte.PECore.tagsUpdated(PECore.java:349) ~[ProjectE-1.18.2-PE1.0.1.jar%23294!/:1.0.1]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraft.server.ReloadableServerResources.m_206868_(ReloadableServerResources.java:95) ~[client-1.18.2-20220404.173914-srg.jar%23376!/:?]
        at net.minecraft.server.WorldStem.m_206901_(WorldStem.java:64) ~[client-1.18.2-20220404.173914-srg.jar%23376!/:?]
        at net.minecraft.client.Minecraft.doLoadLevel(Minecraft.java:1936) ~[client-1.18.2-20220404.173914-srg.jar%23376!/:?]
        at net.minecraft.client.Minecraft.m_91200_(Minecraft.java:1871) ~[client-1.18.2-20220404.173914-srg.jar%23376!/:?]
        at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:473) ~[client-1.18.2-20220404.173
914-srg.jar%23376!/:?]

### Expected behavior
EMC to be generated appropriately.

### To Reproduce
1. Add ProjectE and ProjectE-Integration to ATM7
2. Create new world
3. See latest.log

## Logs
[00:19:25] [Render thread/ERROR]: Error calculating EMC values
java.lang.NoSuchFieldError: heatFrameCooling
        at com.tagnumelite.projecteintegration.addons.PneumaticCraftAddon$PCRHeatFrameCoolingMapper.canHandle(PneumaticCraftAddon.java:195) ~[projecte-integrati
on-1.18.2-5.0.0.jar%23295!/:5.0.0]
        at moze_intel.projecte.emc.mappers.recipe.CraftingMapper.addMappings(CraftingMapper.java:61) ~[ProjectE-1.18.2-PE1.0.1.jar%23294!/:1.0.1]
        at moze_intel.projecte.emc.EMCMappingHandler.map(EMCMappingHandler.java:116) ~[ProjectE-1.18.2-PE1.0.1.jar%23294!/:1.0.1]
        at moze_intel.projecte.PECore.tagsUpdated(PECore.java:349) ~[ProjectE-1.18.2-PE1.0.1.jar%23294!/:1.0.1]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
        at net.minecraft.server.ReloadableServerResources.m_206868_(ReloadableServerResources.java:95) ~[client-1.18.2-20220404.173914-srg.jar%23376!/:?]
        at net.minecraft.server.WorldStem.m_206901_(WorldStem.java:64) ~[client-1.18.2-20220404.173914-srg.jar%23376!/:?]
        at net.minecraft.client.Minecraft.doLoadLevel(Minecraft.java:1936) ~[client-1.18.2-20220404.173914-srg.jar%23376!/:?]
        at net.minecraft.client.Minecraft.m_91200_(Minecraft.java:1871) ~[client-1.18.2-20220404.173914-srg.jar%23376!/:?]
        at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:473) ~[client-1.18.2-20220404.173
914-srg.jar%23376!/:?]

**Comment by TagnumElite** [comment]
This should be fixed in `v5.0.3`
