### ISSUE TITLE
Create Integration Breaks EMC

### ISSUE THREAD

**Issue by rallias** [TagnumElite/ProjectE-Integration#50]
### Prerequisites

- [X] I am running the latest version
- [X] I have made sure there is no duplicate issue

### Details

- MC Version: 1.18.2
- Mod Version: PEI: 5.1.0, Create: 0.50.0

## Description

[12:16:25] [Render thread/ERROR]: Error calculating EMC values
java.lang.NoSuchMethodError: 'net.minecraft.core.NonNullList com.simibubi.create.content.contraptions.processing.ProcessingRecipe.getRollableResults()'
	at com.tagnumelite.projecteintegration.addons.CreateAddon$CreateProcessingRecipeMapper.getOutput(CreateAddon.java:142) ~[projecte-integration-1.18.2-5.1.0.jar%23295!/:5.1.0]
	at com.tagnumelite.projecteintegration.addons.CreateAddon$CreateCrushingMapper.getOutput(CreateAddon.java:178) ~[projecte-integration-1.18.2-5.1.0.jar%23295!/:5.1.0]
	at com.tagnumelite.projecteintegration.addons.CreateAddon$CreateProcessingRecipeMapper.getOutput(CreateAddon.java:68) ~[projecte-integration-1.18.2-5.1.0.jar%23295!/:5.1.0]
	at com.tagnumelite.projecteintegration.api.recipe.ABaseRecipeMapper.convertRecipe(ABaseRecipeMapper.java:60) ~[projecte-integration-1.18.2-5.1.0.jar%23295!/:5.1.0]
	at com.tagnumelite.projecteintegration.api.recipe.ARecipeTypeMapper.handleRecipe(ARecipeTypeMapper.java:66) ~[projecte-integration-1.18.2-5.1.0.jar%23295!/:5.1.0]
	at moze_intel.projecte.emc.mappers.recipe.CraftingMapper.addMappings(CraftingMapper.java:72) ~[ProjectE-1.18.2-PE1.0.1.jar%23294!/:1.0.1]
	at moze_intel.projecte.emc.EMCMappingHandler.map(EMCMappingHandler.java:116) ~[ProjectE-1.18.2-PE1.0.1.jar%23294!/:1.0.1]
	at moze_intel.projecte.PECore.tagsUpdated(PECore.java:349) ~[ProjectE-1.18.2-PE1.0.1.jar%23294!/:1.0.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]

### Expected behavior
EMC should generate without fault.

### To Reproduce
1. Install AllTheMods7 latest version.
2. Add ProjectE and PEI.
3. Observe no EMC generated.

## Logs
[12:16:25] [Render thread/ERROR]: Error calculating EMC values
java.lang.NoSuchMethodError: 'net.minecraft.core.NonNullList com.simibubi.create.content.contraptions.processing.ProcessingRecipe.getRollableResults()'
	at com.tagnumelite.projecteintegration.addons.CreateAddon$CreateProcessingRecipeMapper.getOutput(CreateAddon.java:142) ~[projecte-integration-1.18.2-5.1.0.jar%23295!/:5.1.0]
	at com.tagnumelite.projecteintegration.addons.CreateAddon$CreateCrushingMapper.getOutput(CreateAddon.java:178) ~[projecte-integration-1.18.2-5.1.0.jar%23295!/:5.1.0]
	at com.tagnumelite.projecteintegration.addons.CreateAddon$CreateProcessingRecipeMapper.getOutput(CreateAddon.java:68) ~[projecte-integration-1.18.2-5.1.0.jar%23295!/:5.1.0]
	at com.tagnumelite.projecteintegration.api.recipe.ABaseRecipeMapper.convertRecipe(ABaseRecipeMapper.java:60) ~[projecte-integration-1.18.2-5.1.0.jar%23295!/:5.1.0]
	at com.tagnumelite.projecteintegration.api.recipe.ARecipeTypeMapper.handleRecipe(ARecipeTypeMapper.java:66) ~[projecte-integration-1.18.2-5.1.0.jar%23295!/:5.1.0]
	at moze_intel.projecte.emc.mappers.recipe.CraftingMapper.addMappings(CraftingMapper.java:72) ~[ProjectE-1.18.2-PE1.0.1.jar%23294!/:1.0.1]
	at moze_intel.projecte.emc.EMCMappingHandler.map(EMCMappingHandler.java:116) ~[ProjectE-1.18.2-PE1.0.1.jar%23294!/:1.0.1]
	at moze_intel.projecte.PECore.tagsUpdated(PECore.java:349) ~[ProjectE-1.18.2-PE1.0.1.jar%23294!/:1.0.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]

**Comment by TagnumElite** [comment]
Should be fixed in 5.2.0
