### ISSUE TITLE
Chipped got broken again

### ISSUE THREAD

**Issue by oliverrook** [TagnumElite/ProjectE-Integration#70]
### Prerequisites

- [ X] I am running the latest version
- [ X] I have made sure there is no duplicate issue

### Details

- MC Version: 1.18.2
- Mod Version: 5.4.2

## Description

Chipped EMC values have been broken on existing saves. This results in the entire EMC List being innaccessible if you had a world with chipped loaded before and updated Chipped.

### Expected behavior
Not having EMC values broken.

### To Reproduce
1. Have a world with a previous version of chipped installed
2. Add some blocks from chipped to the transmutation table
3. Update chipped
4. EMC values are all gone in the table

## Logs
`[16:52:37] [Render thread/ERROR]: Error calculating EMC values
java.lang.NoClassDefFoundError: earth/terrarium/chipped/registry/ChippedRecipeTypes
	at com.tagnumelite.projecteintegration.addons.ChippedAddon$ChippedCarpentersTableMapper.canHandle(ChippedAddon.java:104) ~[projecte-integration-1.18.2-5.4.2.jar%23356!/:5.4.2]
	at moze_intel.projecte.emc.mappers.recipe.CraftingMapper.addMappings(CraftingMapper.java:61) ~[ProjectE-1.18.2-PE1.0.1.jar%23355!/:1.0.1]
	at moze_intel.projecte.emc.EMCMappingHandler.map(EMCMappingHandler.java:116) ~[ProjectE-1.18.2-PE1.0.1.jar%23355!/:1.0.1]
	at moze_intel.projecte.PECore.tagsUpdated(PECore.java:349) ~[ProjectE-1.18.2-PE1.0.1.jar%23355!/:1.0.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.server.ReloadableServerResources.m_206868_(ReloadableServerResources.java:95) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.server.WorldStem.m_206901_(WorldStem.java:64) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.Minecraft.doLoadLevel(Minecraft.java:1938) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.Minecraft.m_91200_(Minecraft.java:1873) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:473) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:330) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.client.gui.screens.worldselection.SelectWorldScreen.m_101377_(SelectWorldScreen.java:70) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FpsReducer2-forge-1.18.2-2.0.jar%23225!/:1.18.2-2.0]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2344!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.handler$cni000$handleWaitEventsTimeout(RenderSystem.java:2990) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1071) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23464!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.0.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.ClassNotFoundException: earth.terrarium.chipped.registry.ChippedRecipeTypes
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 49 more`

**Comment by camohax** [comment]
I also had this issue with FTB Industrial Contraptions but on 1.19.2 I still wanted to keep the FTB Industrial Contraptions and use integration. I got it working by opening projecte-integration-1.19.2-6.1.1.jar with WinRar and going to com/tagnumelite/projecteintegration/addons and deleting the files associated with the mod(s) that integrations is having issues with. This made integrations work and just removed the emc values for FTB Industrial Contraptions. So far no issues.

**Comment by Xwartu** [comment]
Can confirm that I was having problems with the classes for BotaniaAddOn$BPureDaisyMapper.Class and FTBIndustrialContraptionsAddon$AFTBMAchineRecipeMapper.class in a server for 1.18.2 that I'm running for me and a friend preventing EMC values from being created by Project E. I deleted the respective classes in the most recent 1.18.2 jar with WinRar as camohax suggested, and went from 0 EMC values to 10,000+. I don't know your (tagnumelite) exact naming scheme, but the FTB class in question has a completely different subsequent moniker, that being AFTB instead of FTBI compared to the rest. I'm curious if it seems to be part of the problem because I remember seeing a Class not found exception.

Side note: seemingly no problems with Chipped however

**Comment by TagnumElite** [comment]
AFTBMachineRecipeMapper is an abstract class inherited by other FTB Industrial Contraption machines. The mod probably updated and broke the code. Botania's PureDaisyMapper has always had an error output but it should'nt have caused any problems (just never really figured that one out).

Also @Xwartu What version of FTB Industrial Contraptions are you using?

**Comment by SDUBZ** [comment]
@TagnumElite it seems you updated it but the version never published https://github.com/TagnumElite/ProjectE-Integration/commit/e8f50bd252d7ee8f212638d4765c10b3c29b71c6
