### ISSUE TITLE
Compatibility with Ice and Fire broke with latest version

### ISSUE THREAD

**Issue by xenogray** [TagnumElite/ProjectE-Integration#75]
### Prerequisites

- [ x ] I am running the latest version
- [ x ] I have made sure there is no duplicate issue

### Details

- MC Version: 1.16.5
- Mod Version: 4.5.1

## Description

Ice and Fire updated very recently and since that update, ProjectE Integration breaks the EMC value of all items (including vanilla).

### Expected behavior
Items have EMC value

### To Reproduce
1. Launch MC with latest ProjectE integration and latest IceAndFire
2. Look at vanilla item
3. No EMC value

## Logs

[latest.log](https://github.com/TagnumElite/ProjectE-Integration/files/10956736/latest.log)

Interesting part of the log file :

[13Mar2023 10:27:17.140] [Worker-Main-5/ERROR] [projecte/]: Error calculating EMC values
java.lang.NoSuchFieldError: ALL_FORGE_RECIPES
	at com.tagnumelite.projecteintegration.addons.IceAndFireAddon$IAFDragonForgeMapper.getRecipes(IceAndFireAddon.java:53) ~[projecteintegration:4.5.1]
	at com.tagnumelite.projecteintegration.api.recipe.PEIRecipeMapper.addMappings(PEIRecipeMapper.java:74) ~[projecteintegration:4.5.1]
	at moze_intel.projecte.emc.EMCMappingHandler.map(EMCMappingHandler.java:106) ~[projecte:PE1.0.2]
	at moze_intel.projecte.emc.EMCReloadListener.func_195410_a(EMCReloadListener.java:30) ~[projecte:PE1.0.2]
	at net.minecraft.resources.IResourceManagerReloadListener.func_232635_a_(IResourceManagerReloadListener.java:18) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]

**Comment by TagnumElite** [comment]
Should be fixed in 4.6.0

**Comment by xenogray** [comment]
[crash-2023-03-15_11.09.12-fml.txt](https://github.com/TagnumElite/ProjectE-Integration/files/10978458/crash-2023-03-15_11.09.12-fml.txt)

Hello,

Just tested, now the server won't start anymore :

-- Head --
Thread: main
Stacktrace:
	at java.lang.Class.asSubclass(Class.java:3640) ~[?:?] {}
-- MOD projecteintegration --
Details:
	Mod File: projecte-integration-1.16.5-4.6.0.jar
	Failure message: ProjectE Integration (projecteintegration) encountered an error during the common_setup event phase
		java.lang.ClassCastException: class com.tagnumelite.projecteintegration.addons.IceAndFireAddon$IAFDragonForgeMapper
	Mod Version: 4.6.0
	Mod Issue URL: https://github.com/TagnumElite/ProjectE-Integration/issues
	Exception message: java.lang.ClassCastException: class com.tagnumelite.projecteintegration.addons.IceAndFireAddon$IAFDragonForgeMapper
Stacktrace:
	at java.lang.Class.asSubclass(Class.java:3640) ~[?:?] {}
	at com.tagnumelite.projecteintegration.api.Utils.createOrGetInstance(Utils.java:73) ~[projecteintegration:4.6.0] {re:classloading}
	at com.tagnumelite.projecteintegration.api.Utils.getCustomRecipeMappers(Utils.java:60) ~[projecteintegration:4.6.0] {re:classloading}
	at com.tagnumelite.projecteintegration.api.recipe.PEIRecipeMapper.loadMappers(PEIRecipeMapper.java:47) ~[projecteintegration:4.6.0] {re:classloading}
	at com.tagnumelite.projecteintegration.PEIntegration.commonSetup(PEIntegration.java:32) ~[projecteintegration:4.6.0] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}


Best regards,
Xeno.

**Comment by TagnumElite** [comment]
yeah, something broke somewhere. Currently busy with this.

**Comment by TagnumElite** [comment]
This should be fixed in version 4.6.1
