### ISSUE TITLE
Crash on server startup with last update

### ISSUE THREAD

**Issue by xenogray** [TagnumElite/ProjectE-Integration#76]
### Prerequisites

- [ x ] I am running the latest version
- [ x ] I have made sure there is no duplicate issue

### Details

- MC Version: 1.16.5
- Mod Version: 4.6.0

## Description

Server crashes on startup with the following error :

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:71) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:37) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49) [forge-1.16.5-36.2.39.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46) [forge-1.16.5-36.2.39.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:43) [forge-1.16.5-36.2.39.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: main
Stacktrace:
	at java.lang.Class.asSubclass(Class.java:3640) ~[?:?] {}
-- MOD projecteintegration --
Details:
	Mod File: projecte-integration-1.16.5-4.6.0.jar
	Failure message: ProjectE Integration (projecteintegration) encountered an error during the common_setup event phase
		java.lang.ClassCastException: class com.tagnumelite.projecteintegration.addons.IceAndFireAddon$IAFDragonForgeMapper
	Mod Version: 4.6.0
	Mod Issue URL: https://github.com/TagnumElite/ProjectE-Integration/issues
	Exception message: java.lang.ClassCastException: class com.tagnumelite.projecteintegration.addons.IceAndFireAddon$IAFDragonForgeMapper
Stacktrace:
	at java.lang.Class.asSubclass(Class.java:3640) ~[?:?] {}
	at com.tagnumelite.projecteintegration.api.Utils.createOrGetInstance(Utils.java:73) ~[projecteintegration:4.6.0] {re:classloading}
	at com.tagnumelite.projecteintegration.api.Utils.getCustomRecipeMappers(Utils.java:60) ~[projecteintegration:4.6.0] {re:classloading}
	at com.tagnumelite.projecteintegration.api.recipe.PEIRecipeMapper.loadMappers(PEIRecipeMapper.java:47) ~[projecteintegration:4.6.0] {re:classloading}
	at com.tagnumelite.projecteintegration.PEIntegration.commonSetup(PEIntegration.java:32) ~[projecteintegration:4.6.0] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

### Expected behavior
Not crash, I suppose.

### To Reproduce
1. Update mod
2. Start server
3. Crash

## Logs
[crash-2023-03-15_11.09.12-fml.txt](https://github.com/TagnumElite/ProjectE-Integration/files/10978583/crash-2023-03-15_11.09.12-fml.txt)

**Comment by TagnumElite** [comment]
Oh yes, I updated support for Ice And Fire so you need the latest version of ice and fire

**Comment by TagnumElite** [comment]
Wait, just tested this. I see there is a problem. Will look into this right now

**Comment by TagnumElite** [comment]
This should be fixed in version 4.6.1

**Comment by xenogray** [comment]
All is good now, thank you very much ! :)
