### ISSUE TITLE
Avaritia(1.2x or Reforged)Error calculating EMC values

### ISSUE THREAD

**Issue by BossOfKillers** [TagnumElite/ProjectE-Integration#86]
### Prerequisites

- [x] I am running the latest version
- [x] I have made sure there is no duplicate issue

### Details

- MC Version: 1.18.2 (Forge 40.2.0 and 40.2.9[Latest])
- Mod Version: 5.4.6{Tried with 5.4.4, 5.4.2(Both), 5.4.1 as well)

## Description

EMC Values are gone when paired with either [Avaritia:Reforged](https://www.curseforge.com/minecraft/mc-mods/avaritia-reforged) or [Avaritia1.2x](https://www.curseforge.com/minecraft/mc-mods/avaritia1-2x)

### Expected behaviour
Error calculating EMC values

### To Reproduce
Steps to reproduce the behaviour:
1. Launch MC with PEI and either of the 2 mods
2. Enter a world
3. EMC Values don't appear and you can't use the Transmutation Table

## Logs
[latest.log](https://gist.github.com/BossOfKillers/ee8a977439f374639cb3b13403ab46e3)

![Untitled](https://github.com/TagnumElite/ProjectE-Integration/assets/105159832/6df00fdb-280d-420a-8d95-5ec13a6f1d3c)

**Comment by TagnumElite** [comment]
I will have a look at supporting [Avaritia:Reforged](https://www.curseforge.com/minecraft/mc-mods/avaritia-reforged).

**Comment by Ocawesome101** [comment]
Bumping because a friend and i are having this issue too.  We're using ProjectE: Integration version 5.6.2 on Minecraft 1.18.2. Here's the relevant section of the server's `debug.log`:

```
[23Oct2023 01:43:12.577] [main/ERROR] [projecte/]: Error calculating EMC values                                                                                                                                                                
java.lang.NoClassDefFoundError: morph/avaritia/init/AvaritiaModContent                                                                                                                                                                         
  at com.tagnumelite.projecteintegration.addons.AvaritiaAddon$AvaritiaCompressorMapper.canHandle(AvaritiaAddon.java:58) ~[projecte-integration-1.18.2-5.6.2.jar%23123!/:5.6.2]                                                                 
  at moze_intel.projecte.emc.mappers.recipe.CraftingMapper.addMappings(CraftingMapper.java:61) ~[ProjectE-1.18.2-PE1.0.1.jar%23122!/:1.0.1]                                                                                                    
  at moze_intel.projecte.emc.EMCMappingHandler.map(EMCMappingHandler.java:116) ~[ProjectE-1.18.2-PE1.0.1.jar%23122!/:1.0.1]                                                                                                                    
  at moze_intel.projecte.PECore.tagsUpdated(PECore.java:349) ~[ProjectE-1.18.2-PE1.0.1.jar%23122!/:1.0.1]                                                                                                                                      
  at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]                                                                                                                                        
  at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]                                                                                                                               
  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]                                                                                                                                                
  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]                                                                                                                                                
  at net.minecraft.server.ReloadableServerResources.m_206868_(ReloadableServerResources.java:95) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]                                                                                            
  at net.minecraft.server.WorldStem.m_206901_(WorldStem.java:64) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]                                                                                                                            
  at net.minecraft.server.Main.main(Main.java:190) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?]                                                                                                                                          
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]                                                                                                                                                               
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]                                                                                                                                             
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]                                                                                                                                     
  at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]                                                                                                                                                                                   
  at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.10.jar%2318!/:?]                                                                       
  at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]                                                                                                          
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]                                                                                                                            
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]                                                                                                                            
  at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]                                                                                                                                                      
  at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]                                                                                                                                                      
  at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]                                                                                                                      
  at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]                                                                                                                      
  at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]                                                                                                                             
Caused by: java.lang.ClassNotFoundException: morph.avaritia.init.AvaritiaModContent                                                                                                                                                            
  at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]                                                                                                                                                      
  at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
  at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-1.0.8.jar:?]                                                                                                                                       
  at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]                                                                                                                                                                              
  at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-1.0.8.jar:?]                                                                                                                                       
  at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]                                                                                                                                                                              
  ... 24 more
```
