### ISSUE TITLE
Mod deletes all items EMC values, and I cannot insert an item into the transmutation table

### ISSUE THREAD

**Issue by Hithere21** [TagnumElite/ProjectE-Integration#92]
### Prerequisites

- [x] I am running the latest version
- [x] I have made sure there is no duplicate issue

### Details

- MC Version: 1.19.2 
- Mod Version: 6.2.0
- Performed on previously generated world without ProjectE initially installed
- Alex's mobs also has a transmutation table, not sure if that has anything to do with it however figured it was worth noting
- Performed in a modpack from Curseforge

## Description

When used in conjunction with ProjectE, all EMC values for all items will dissapear. Mod completely removes all EMC values of all items, and I cannot put any items into the transmutation table. All other things with ProjectE works, however EMC values are bugged. I still am able to get all items from ProejctE, but EMC values do not work. 

### Expected behavior
Expected all EMC values to show, however no EMC values showed

### To Reproduce
1. 
2. 
3. Then This 

## Logs

- latest.log
- crash-\*.log (if applicable)

**Comment by TheAnachronism** [comment]
I've got a similar behaviour.
Loading in the mod causes the `custom_emc.jcon` file to be completely empty, and no items to have an EMC value.

First I thought it was because of another mod, **Quark**, as it makes some changes to the vanilla items, but removing that doesn't seem to have fixed it.

**Comment by EnderEmo** [comment]
Similar issue,
MC version: 1.18.2
Projecte: PE1.0.1
Projecte integration: 5.4.6

I have enabled dumpEverythingToFile and pregenerate in the ProjectE config, to view what gets generated by ProjectE, before installing the mod both of them got generated.
Upon adding the mod, ProjectE doesn't generate pregenerated_emc.json and mappingdump.json, it will not load any emc value from custom_emc.json and pregenerated_emc.json

**Comment by KatoNamus** [comment]
I have a similar issue on 1.19.2 , mod v 6.20. Mine throws out an exception with ProjectE's mapping.
Let me know if you'd like a full debug.log and/or latest.log, else here's just the applicable stack trace:

`java.lang.NoSuchFieldError: AIR_MILL_GRINDING
	at com.tagnumelite.projecteintegration.addons.ElementalCraftAddon$ECGrindingMapper.canHandle(ElementalCraftAddon.java:127) ~[projecte-integration-1.19.2-6.2.0.jar%23917!/:6.2.0]
	at moze_intel.projecte.emc.mappers.recipe.CraftingMapper.addMappings(CraftingMapper.java:64) ~[ProjectE-1.19.2-PE1.0.1B.jar%23916!/:1.0.1B]
	at moze_intel.projecte.emc.EMCMappingHandler.map(EMCMappingHandler.java:117) ~[ProjectE-1.19.2-PE1.0.1B.jar%23916!/:1.0.1B]
	at moze_intel.projecte.PECore.tagsUpdated(PECore.java:339) ~[ProjectE-1.19.2-PE1.0.1B.jar%23916!/:1.0.1B]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraft.server.ReloadableServerResources.m_206868_(ReloadableServerResources.java:101) ~[client-1.19.2-20220805.130853-srg.jar%231051!/:?]
	at net.minecraft.server.WorldLoader.m_214372_(WorldLoader.java:35) ~[client-1.19.2-20220805.130853-srg.jar%231051!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%231051!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%231051!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%231051!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19.2-20220805.130853-srg.jar%231051!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072) ~[client-1.19.2-20220805.130853-srg.jar%231051!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%231051!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%231051!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%231051!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]`

**Comment by TagnumElite** [comment]
Without logs I can see what the issue is. I believe have just fixed @KatoNamus problem with release 6.3.2 though.

**Comment by KatoNamus** [comment]
> Without logs I can see what the issue is. I believe have just fixed @KatoNamus problem with release 6.3.2 though.

It's working beautifully now. Thank you very much!
